### ISSUE TITLE
Can not display the image after selecting in safari-5.1.7 and win-7

### ISSUE THREAD

**Issue by subhrajyotiw5rtc** [danialfarid/ng-file-upload#1672]
Hi,I am getting one error while trying to display image after selecting using safari-5.1.7 and win-7.

Error:

```
'undefined' is not a function (evaluating 'FileAPI.readAsDataURL(a,d)')
/js/ng-file-upload-shim.min.js:2

```

I am explaining my code below.

```

 <div ng-class="{'myError': billdata.upload_{{$index}}.$touched && billdata.upload_{{$index}}.$invalid }">
<input type="file" class="filestyle form-control" data-size="lg" name="upload_{{$index}}" id="bannerimage_{{$index}}"  ng-model="mul.image" ngf-pattern="'image/*'" accept="image/*" ngf-max-size="2MB" ngf-select="onFileSelect1($index);">
<div style="clear:both;"></div>
 </div>
 </div>
 <span class="input-group-btn" ng-show="mulImage.length>0">
<img ngf-thumbnail="mul.image" name="pro" border="0" style="width:32px; height:32px; border:#808080 1px solid;" ng-if="mul.image !=null"><img ng-src="upload/{{mul.filename}}" name="pro" border="0" style="width:32px; height:32px; border:#808080 1px solid;" ng-if="mul.filename!=''">

```

Here after selecting the image this  should display and its working fine in other browser but not working in given environment. i checked some solution from here regarding this type issue but that did not help me.Here is my [Plunkr](https://plnkr.co/edit/8o77L0WKGIb1yK0a0NBi?p=preview) sample code its not working in safari 5.1.7 and win-7.Please help me to fix this issue.

**Comment by danialfarid** [comment]
Does it work if you change ngf-thumbnail to ngf-src?

**Comment by subhrajyotiw5rtc** [comment]
I tried to change both but its not working.Actually its not retrieving any file blob url from drive for this work around only. Do you have any working solution ?

**Comment by danialfarid** [comment]
The error seems like you are not loading the FileAPI files properly. Are they loaded in the network tab?

**Comment by hb-aravind** [comment]
I too have the same error in safari(WIN 7), also added your FileAPI and also FileAPI-flash files before file-upload-shim.js, as someone mentioned online, but still the issue persists.

**Comment by rajguru827** [comment]
uploading same file twice is not working in windows safari.

**Comment by scripterkaran** [comment]
+1 This thing still persist on mac safari, even after changing to ngf-src

**Comment by ryanhinton** [comment]
I'm experiencing the issue with Safari, regardless of OS.  I have tested this on an iPad, Mac and Windows 10.  The thumbnails never come into view.  However, they remain hidden and if I mouse over the area the thumbnail should be located, my cursor becomes a hand, but clicking it does nothing, either.  I don't know what the problem is.  All other browsers work correctly and show the thumbnails after selected except for Safari.
