### ISSUE TITLE
TypeError: files.splice is not a function

### ISSUE THREAD

**Issue by lvtrvd** [danialfarid/ng-file-upload#994]
I am getting this error when I am using the ng-file-upload. Can you please let me solution for removing this error.
TypeError: files.splice is not a function
at validateSync (ng-file-upload.js?body=1:825)

**Comment by danialfarid** [comment]
Copy your code or create a jsfiddle for faster answer.

**Comment by PuneeshGoyal** [comment]
Here is my  code

**Comment by danialfarid** [comment]
This seems to be fine. Create a jsfiddle or live demo showing the error. It might be a conflict with other plugins

**Comment by LokeshBoran** [comment]
did you find any solution

**Comment by Bodom78** [comment]
I just got this error too.

Seems to occur when you set the ng-model and it's null or undefined. Making it an empty array by default stops the error.

**Comment by lvtrvd** [comment]
Yes, the ng-modal is null. Let me try the solution

**Comment by Bodom78** [comment]
Scrap my previous comment.

Setting it to an empty array stops the initial error but causes another ([].splice is not a function) when selecting a file to upload.

I've only started using this but it seems to look for a "files" attribute so:

Fails
`current model ng-model="data.profile_picture"`

Works
`current model ng-model="data.profile_picture.files"`

**Comment by danialfarid** [comment]
What version of the plugin are you using? try to upgrade to the latest version.

**Comment by Bodom78** [comment]
I just set it up today and got the latest 7.3.8

After adding a "file" or "files" key onto the ng-model it's all working fine.

**Comment by jbennie** [comment]
version 8.0.1  - but the error is specific to firefox (40.0.3) on mac, it works fine on firefox (40.0.3) on pc.

**Comment by danialfarid** [comment]
That is weird. If you want a fix in the plugin release create a jsfiddle so I could debug and figure out what is causing it.

**Comment by danialfarid** [comment]
Closing this until steps to reproduce or sample jsfiddle is created.

**Comment by lazarov1994** [comment]
God bless you @Bodom78 I have not notice that ng-model is not an f*ckin empty array.

**Comment by bondneverdies** [comment]
Here is a jsfiddle reproducing the issue : http://jsfiddle.net/xqrrzu2k/3/

**Comment by danialfarid** [comment]
You are setting a url as the file model. File model should only contain `File` objects.

**Comment by bondneverdies** [comment]
Well, I think you must clarify this point in the documentation. I was not able to find any informations about `File` objects in the README and I don't know how to deal with them.

**Comment by danialfarid** [comment]
File object is standard javascript object. It kind of seems obvious that the model that you assign to input type file will contain files not string urls.
Anyway it is documented here now in case other people have the same issue.

**Comment by azuax** [comment]
Hi @danialfarid , just a question. How can I handle an update where my file from the database gives me an url? Thanks in advance.

**Comment by danialfarid** [comment]
@azuax  Please post a separate issue or ask it on stackoverflow. It is not related to this question. There are already some existing issues about this.

**Comment by mryraghi** [comment]
@danialfarid could you please explain me how should I set up a File object with an URL, please? 

This is what I have:
```html
<img ngf-select ng-model="formData.picture"
         name="picture"
         ngf-pattern="'image/*'"
         accept="image/*" ngf-max-size="1MB"
         ngf-min-height="300"
         ngf-src="formData.picture"
         ngf-background="formData.picture"
         class="img-circle img-circle_edit">
```

I've set $scope.formData.picture to be a default image in my controller. The image is clickable in order to select an image...but when the page loads i have this error: 

```TypeError: files.splice is not a function
    at validateSync (app/client/lib/ngFileUpload/meteor:/💻app/client/lib/ngFileUpload/ng-file-upload.min.js:1099)
    at [object Object].upload.validate (app/client/lib/ngFileUpload/meteor:/💻app/client/lib/ngFileUpload/ng-file-upload.min.js:1110)
    at Array.<anonymous> (app/client/lib/ngFileUpload/meteor:/💻app/client/lib/ngFileUpload/ng-file-upload.min.js:1037)
    at Object.ngModelWatch (packages/meteor:/💻app/packages/angular_angular/angular.js:25419)
    at Scope.$digest (packages/meteor:/💻app/packages/angular_angular/angular.js:15818)
    at Scope.$apply (packages/meteor:/💻app/packages/angular_angular/angular.js:16097)
    at HTMLButtonElement.<anonymous> (packages/meteor:/💻app/packages/angular_angular/angular.js:23554)
    at HTMLButtonElement.jQuery.event.dispatch (packages/meteor:/💻app/packages/jquery/packages/jquery.js:4673)
    at HTMLButtonElement.elemData.handle (packages/meteor:/💻app/packages/jquery/packages/jquery.js:4341)```

As you previously said, setting ng-model as an URL is wrong. Could you please tell me how should I set up a File object *with* an URL? Thank you :+1:

**Comment by danialfarid** [comment]
URL is different from the file so keep them in two different model objects like formData.picture and formData.pictureUrl.

**Comment by mryraghi** [comment]
Ok, this is a good idea! :+1: now I have no errors coming out but how can I preview the selected file now?

```<img ngf-select ng-model="formData.picture"
         name="picture"
         ngf-pattern="'image/*'"
         accept="image/*" ngf-max-size="1MB"
         ngf-min-height="300"
         ngf-src="formData.pictureURL"
         ngf-background="formData.pictureURL"
         class="img-circle img-circle_edit">```

**Comment by danialfarid** [comment]
`ngf-src="formData.picture || formData.pictureURL"`

**Comment by mryraghi** [comment]
:+1: :100: thank you
